/* Write your PL/SQL query statement below */
SELECT(
    CASE WHEN MOD( COUNT, 2 ) = 1  AND ID = COUNT THEN ID
	WHEN MOD( ID, 2 ) = 1 THEN ID + 1
	ELSE ID - 1  END
	) AS ID, STUDENT
	FROM SEAT, ( SELECT COUNT( * ) AS COUNT FROM SEAT ) C
    ORDER BY ID;